### ISSUE TITLE
Detect absence of log statements

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#101]
If a log statement is not detected in the actual log, its branch should be labeled "must-not"

**Comment by mdu2017** [comment]
It seems that if we want to label an entire path/branch, we can add another property for the path to check if that branch is a must/may/must-not, since currently only the constraints within each branch are labeled. If during labeling we check if a log is not detected, we can label that particular block as a must not, and during traversal we check to see if a particular path has an absence of a log (must-not), then we can most likely exclude it from the final list of paths. There may be something I am overlooking, but this seems like a good approach to start with.
