### ISSUE TITLE
Create regex for each found logging string

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#3]
For each possible log message, we must create a regular expression that matches it.

**Comment by RussellSanders1** [comment]
Calls to Msg only accept a single string arugment, so the string itself will be the only information we will need to match, so a real regex is not needed here. Nice!

Calls to Msgf are where things get interesting, because here, variable data can be formatted for the log and we will need to figure how to extract the regex from these calls. @mdu2017

**Comment by mdu2017** [comment]
For Msgf does the regex need to match just the actual string content, or the names of the variables?

ex: log.Info().Msgf(databasePreparationMessage, prepDbExitCode)
 - the first argument is just a variable that contains a string
 - the second argument is a number returned from a function.

**Comment by vinbush** [comment]
For msgf, you have to match the string content, including formatting characters. In your example,
databasePreparationMessage = "database preparation exited with error code %v"
you have to have a regex that matches "database preparation exited with error code " followed by an int (so something like 'database preparation exited with error code \d+')
