### ISSUE TITLE
Add variable nodes representing function arguments

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#49]
When a function call happens, we need to look at the list of arguments in the function call, and the list of parameters in the function declaration. For each parameter, make a variable node that assigns the argument value to the parameter variable. For example:

```
someFunc(x, y, z)

func someFunc(a, b, c) {
    // body
}
```

Before: a function call in the tree, not yet connected to its declaration
```
{FunctionNode, someFunc, [x, y, z]} ->
{next child}
```

After: the function node flows to a variable node for each parameter, assigning as the expression the argument
```
{FunctionNode, someFunc, [x, y, z]} ->
{VariableNode, varname: a, expr: x} ->
{VariableNode, varname: b, expr: y} ->
{VariableNode, varname: c, expr: z} ->
{FunctionDecl, someFunc, [a, b, c]} ->
{function body here}
```

**Comment by RussellSanders1** [comment]
added TODOs where functionality will go when classes become available

**Comment by RussellSanders1** [comment]
Idea to reduce adding new nodes to the chain: instead of linking them after the FunctionNode, just add the relationship to the Args map of FunctionNode directly

{FunctionNode, someFunc, 
[
{VariableNode, varname: a, expr: x}, 
{VariableNode, varname: b, expr: y}, 
{VariableNode, varname: c, expr: z}
]
} ->
{FunctionDecl, someFunc, [a, b, c]} ->
{function body here}
