### ISSUE TITLE
Create path representation from constraints

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#54]
Given our tree, extract the constraints to make a path of every possible path through the trace

**Comment by RussellSanders1** [comment]
Going to throw some ideas down here for discussion.

The most straightforward way to do it would probably be to traverse through the tree by parents, and anytime a conditional is encountered, parse the statement to determine which variables are being used in that statement, and keep a list of the condition as well as the variables used inside.  Continue to traverse up the tree doing this.  The reason for the list of variables in conditions is to keep track of when and what these variables are assigned to gather information about their values.  When a variable is assigned a value from another variable that variable needs to be added to the list of variables to track moving forward.
This should be done only on the branch(es) labeled as "must" or the immediate "may-have" if no "must" is available (conditionals that completed with no indication of execution).


Alternatively, we could start at the top and work our way down by the same rules, though this is likely to create more overhead because all variables would need to be tracked from the start, which would be more update checking, so I don't think this is the way to do it, just throwing it out there in case there may be a benefit to this traversal order.


Since no changes to the tree are being made at this stage, and we are looking for specific instances of information, a recursive function that builds and adds to slices containing the information we want seems appropriate, and the parts would be::

1. collecting conditional statements

collecting conditional statements
parsing out variables from those statements, and collecting references to variables in the list and adding any associated variables to the list

**Comment by vinbush** [comment]
Sounds good; we also need to actually store the conditions that make up the paths. I recommend a depth-first search; every time you encounter a conditional/assignment, add its condition/assignment expression to a slice representing the current path. When you reach the end of the tree, add the current slice to the collection of all paths (a slice of slices), then let it recurse through the branches with the same rules Russell mentioned.
