### ISSUE TITLE
Connect function calls in CFG tree

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#67]
Function bodies need to be spliced into the CFG tree when calls are found

**Comment by RussellSanders1** [comment]
Named functions are fine, we are currently focusing on literals passed as arguments, a combination of this issue and connecting variables between function calls.  Assigning Jacob to provide help with parsing the ast nodes.

**Comment by RussellSanders1** [comment]
The last leg of this involves integrating calls on objects that get data fields.  obj.GetData() should be represented as obj.data when concerning ourselves with variables collection.

**Comment by RussellSanders1** [comment]
The issue is that the selector expression obj.GetData() , where X = obj, Sel = GetData() has no immediate connection to the function that is called, but instead has the folowing memory relationships:

`obj.GetData()` is a CallExpr node, and

```
func (obj *SomeObj) GetData() int {
    return obj.data
}
```
is a FuncDecl node.


the CallExpr.Fun.(*ast.SelectorExpr).X.Obj.Decl.(*ast.AssignStmt).Rhs[0].(*ast.CompositeLit).Type.Obj
is the same memory address as the FuncDecl.Recv.List[0].Type.(*ast.StarExpr).X.Obj
this is the relationship for the simple case that the object used as a receiver is the only Rhs entry of the above relationship.  Otherwise, this
 ```
(a, b, c) := SomeObj{}, SomeObj{}, SomeObj{}
b.GetData()
```
 becomes more complex and we would need to match identifiers or some other way to tell which entry is the one
we are concerned with (in the above case, we would want Rhs[1] for example).

This also increases in complexity if the object contains composites/structs that have their own data fields with
getters.

```
type Node struct{
    next *Node
    data int
}

func (n *Node) getData() int{
    return n.data
}

func (n *Node) getNext() *Node {
    return n.next
}

func main() {
    __n.getNext().getData()__
}
```
this is the situation I am talking of, where the result should be that were are concerned with n.next.data.

I have no clue where to begin on this, as it seems pretty complex and fragile even for a simple example.  Any help would be much appreciated

**Comment by RussellSanders1** [comment]
This current issue also extends parallel to the issue of connecting any method called on an object, especially complex ones, that may alter values in the object (think like how our recursive functions operate on our linked list)

**Comment by RussellSanders1** [comment]
Additionally, a separate but likely similar memory relationship will need to be found for receivers who are not pointers, though we will not need to track variable changes in those methods, only associate returns from getters like obj.GetData() => obj.data
