### ISSUE TITLE
Filter Z3 assignments to "user inputs"

### ISSUE THREAD

**Issue by vinbush** [cloudhubs/sourcecrawler#91]
We need to filter the assignments that Z3 returns to those that are user inputs (or approximately what the user input is, since we can't be 100% sure what is intended as input from our current analysis). One idea: any variable in the Z3 conditions that is never assigned to anything can be assumed to be input.

**Comment by nnazo** [comment]
I've been giving some thought to how to approach the issue of including only some of the function parameters inside of the z3 assignments filtered to user input only.

Since we have all the conditions and unfiltered assignments after doing the z3 analysis, most of the non-user input can be filtered out by just checking if it has an assignment. The problem with function parameters is that I'm unable to tell what argument matches to the parameter, so I'm as far as I can see we can't tell unless we can know that argument identifier (and figure out whether that one is user input or not, the answer to that one being the same as the answer for the parameter).

And as far as I remember, we either dropped the idea to connect call arguments to their parameters, or never got around to it.

**Comment by vinbush** [comment]
I seem to remember there being a map that connected the arguments to parameters? Did that never get implemented?

**Comment by nnazo** [comment]
That somehow completely crossed my mind when I was thinking through this problem and I hadn't taken another look through the code. That part is implemented.

**Comment by vinbush** [comment]
If that's available, then we just have to traverse up through the param->arg mappings, and if something isn't assigned along that chain, then it is an input.
